services:
  todo-service:
    extends:
      file: compose.yml
      service: todo-service
    image: virabshetkar/todo-service:debug
    build:
      context: .
      target: debug
    environment:
      - ASPNETCORE_URLS=http://+:8080 # '+' is required for host binding 
      - ASPNETCORE_ENVIRONMENT=Development
      - USE_REMOTE_CONFIG=true
      - REMOTE_CONFIG_URL=http://reverse-proxy/config/services/todo-service/ # Trailing slash is required
      - WAIT_FOR_DEBUGGER=true # Required when debugging else turn this off 
    ports:
      - 5002:8080
    networks:
      - local-debug
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    volumes:
      - ./bin/Debug/net9.0/publish:/app/:ro
    command: [ "Service.Todo.dll" ]

networks:
  local-debug:
    external: true
