name: Angular Build

on: workflow_dispatch

jobs:
  build:
    uses: virabshetkar-org/pipeline-templates/.github/workflows/main.yml@main
    with:
      artifact_name: todo
      base_href: /todo-client/
  
