name: Server CI
run-name: ${{github.sha}} - Server

on: 
  push:
    branches:
      - main
    paths:
      - 'server/**'
  workflow_dispatch:

jobs:
  build:
    uses: virabshetkar-org/pipeline-templates/.github/workflows/server-build.yml@main
    with:
      name: todo-service
