name: Server CI
run-name: ${{github.ref}} Server

on: workflow_dispatch

jobs:
  build:
    runs-on: [self-hosted, build]
    steps:
      - name: Clone repo
        uses: actions/checkout@v6
        with:
          path: application
      - name: Docker build
        run: docker build -t virabshetkar/todo-service:${{github.ref}} .
        working-directory: application/server
